http {
    server {
        listen 80;
        server_name remusenerji.com www.remusenerji.com;

        location /mailing/ {
            proxy_pass https://mailing.remusenerji.com/;
       }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html =404;
            
            include /etc/nginx/mime.types;
        }


    }
}

events {}
